# Netlify configuration file
# This file defines the build settings for different environments

# Base settings that apply to all contexts
[build]
  base = "/"
  command = "npm install && npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CRAFT_URL = "https://api.nuxt-starter.yourdomain.com"
  SITE_NAME = "Nuxt Starter"

# Production context: master branch
# This is the default context when a deploy is triggered
[context.production]
  command = "npm install && npm run generate"

[context.production.environment]
  BASE_URL = "https://nuxt-starter.netlify.app"

# Deploy Preview context: Pull/Merge requests
# This context represents a preview of the site when a pull/merge request is opened
[context.deploy-preview]
  command = "npm install && npm run build"

[context.deploy-preview.environment]
  BASE_URL = "https://nuxt-starter-preview.netlify.app"

# Branch Deploy context: Any branch that's not master
# This context represents a deploy from a branch other than master
[context.branch-deploy]
  command = "npm install && npm run build"

[context.branch-deploy.environment]
  BASE_URL = "https://nuxt-starter.netlify.app"

# Specific branch context: dev branch
# This overrides the branch-deploy context for the dev branch
[context.dev]
  command = "npm install && npm run build"

[context.dev.environment]
  BASE_URL = "https://nuxt-starter.netlify.app"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Environment variable inheritance
# Each context inherits variables from the main build environment
# You can override them in each context as needed
