# Netlify configuration file
# This file defines the build settings for different environments

# Base settings that apply to all contexts
[build]
  base = "/frontend"
  command = "npm install && npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CRAFT_URL = "https://api.nuxt-starter.yourdomain.com"
  SITE_NAME = "Nuxt Starter"

# Production context: master branch
# This is the default context when a deploy is triggered
[context.production]
  command = "npm install && npm run generate"

[context.production.environment]
  BASE_URL = "https://nuxt-starter.netlify.app"

[context.preview.environment]
  BASE_URL = "https://nuxt-starter-preview.netlify.app"

# Staging context: staging branch, update this if you have a different branch for staging
[context.staging.environment]
  BASE_URL = "https://nuxt-starter-staging.netlify.app"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Environment variable inheritance
# Each context inherits variables from the main build environment
# You can override them in each context as needed
